apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: vdm
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: minio-init
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MinIO..."
              until mc alias set local http://minio-service:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                sleep 3
              done
              mc mb --ignore-existing local/vdm-media
              mc anonymous set download local/vdm-media
              echo "Done"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: vdm-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vdm-secrets
                  key: MINIO_SECRET_KEY
